### ISSUE TITLE
[Malpedia] Error:root:error in malpedia API health check

### ISSUE THREAD

**Issue by TlcTac** [OpenCTI-Platform/connectors#153]
## Description

Error when launching the Malpedia connector.

## Environment

OS : Linux Mint 19.1 Tessa
OpenCTI version: OpenCTI 3.3.0
Malpedia version : opencti/connector-malpedia:3.3.0

## Reproducible Steps

1. Modify the docker-composite to add the malpedia connector : 
![image](https://user-images.githubusercontent.com/32235552/83248982-3095fb00-a1a6-11ea-82fb-b91c150e1c87.png)

2. Launch the OpenCTI tool with the command : 
`sudo docker-compose --compatibility up`

## Actual Output

Here's the current output: 
![image](https://user-images.githubusercontent.com/32235552/83249116-64712080-a1a6-11ea-8a4c-0f7b0c069cf7.png)
 
I've tested with and without API key, same error.
Thank you for your help !

**Comment by rhaist** [comment]
It seems like the initial health check fails which could indicate that the container can not connect to the internet. Do you have a host-only docker setup?

**Comment by TlcTac** [comment]
Not as far as I know. And I didn't have a problem with the other connectors.
If I look at the docker's network, with `docker network ls`, nothing suggests it : 
![image](https://user-images.githubusercontent.com/32235552/83254303-e2d1c080-a1ae-11ea-8020-e479486d32a2.png)

**Comment by garanews** [comment]
I have same error:
`INFO:root:Listing Threat-Actors with filters null.
INFO:root:Starting ping alive thread
INFO:root:loaded malpedia config: {}
ERROR:root:error in malpedia API health check
INFO:root:Reading Marking-Definition {marking-definition--f88d31f6-486f-44da-b317-01333bde0b82}.
INFO:root:Listing Stix-Domain-Entities with filters [{"key": "name", "values": ["Malpedia"]}].
INFO:root:starting Malpedia connector...
ERROR:root:'version'
`

And other connectors such as alient vault are working

**Comment by rhaist** [comment]
Can you try set the following config parameter and try again:

`MALPEDIA_BASE_URL=https://malpedia.caad.fkie.fraunhofer.de/`

I removed it because it should default in the code but give it a try please.

**Comment by TlcTac** [comment]
Unfortunately it's not working. 
Besides, by relaunching Malpedia several times, I made another error, maybe this can help you?
![image](https://user-images.githubusercontent.com/32235552/83271902-c3489100-a1ca-11ea-9dc9-a8cd43c0c9dc.png)

But most of the time I get this error (detailed above) : 
`ERROR:root:error in malpedia API health check
[...]
ERROR:root:'version'`

**Comment by rhaist** [comment]
It tries to resolve ....frauenhofer.fr but it should be frauenhofer.de. This smells like DNS problems.

**Comment by TlcTac** [comment]
Indeed, I made a mistake when I copied your url in docker-compose.yml

**Comment by garanews** [comment]
FYI outside the docker launched script manually and it works.
Inside the docker also launching manually same error.

**Comment by SamuelHassine** [comment]
We just merged the fix, could you please try with the `rolling` version of the Docker image?

**Comment by TlcTac** [comment]
I just tested with the rolling version you updated but the error is still there for me.
(I checked before the digest was the same of rolling version you updated two days ago)

**Comment by secufred** [comment]
Got the same error

**Comment by secufred** [comment]
I'll try to investigate this but I got a workaround linked to this specific 'error version' ... the issue seems ( at least to be in the function current_version
I've replaced the return int(...) by a return 5757 ( which is the current version number ) 
then it's going further so probably some issues in the parsing of the response from the website

**Comment by secufred** [comment]
empty token ( or invalid token ) seems to give back a {'detail': 'Invalid token.'} , so no version details accessible

**Comment by secufred** [comment]
solved my issue by removing the " around the API key 
->  MALPEDIA_AUTH_KEY=azertyuio in place of MALPEDIA_AUTH_KEY="azertyuio"
for the empty key, still need to investigate

**Comment by SamuelHassine** [comment]
@secufred: we just released the 3.3.1 version of the connector, it should the problem in any case. Please let us know!

**Comment by rhaist** [comment]
You are right @secufred : the example docker compose should say:

```
      - MALPEDIA_AUTH_KEY= # Empty key only fetches TLP:WHITE information
```

The `""` need to be removed. I'll fix the documentation and the example file.

If I test the API with curl and no auth key I can access the version so this is not the problem:

```
$ curl "https://malpedia.caad.fkie.fraunhofer.de/api/get/version"
{"date":"2020-06-05T10:27:06Z","version":5757}
```

**Comment by secufred** [comment]
@rhaist : please do the same for the valhalla one :), I did indeed fixed it for both by removing the "
