### ISSUE TITLE
Unable to connect to MISP

### ISSUE THREAD

**Issue by PyRain** [OpenCTI-Platform/connectors#28]
**Description**

In connector-misp_1, we receive the following error:

"connector-misp_1     | Request body: connector-misp_1     | {"returnFormat": "json", "tags": {"AND": ["OpenCTI:\\ Import"], "NOT": ["OpenCTI:\\ Imported"]}, "withAttachments": 0, "metadata": 0, "enforceWarninglist": 0, "includeEventUuid": 0, "sgReferenceOnly": 0, "includeContext": 0, "headerless": 0, "includeSightings": 0, "includeCorrelations": 0}
connector-misp_1     | Response (if any):
connector-misp_1     | {"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/restSearch"}
connector-misp_1     | CRITICAL:pymisp:Unknown error: the response is not in JSON.
connector-misp_1     | Something is broken server-side, please send us everything that follows (careful with the auth key):
connector-misp_1     | Request headers:
connector-misp_1     | {'User-Agent': 'PyMISP 2.4.112 - Python 3.6', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Length': '290', 'Authorization': 'hXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'content-type': 'application/json'}
."

**Environment**

1. OS: Centos 7
2. OpenCTI version:OpenCTI 1.1.2
3. OpenCTI client: frontend or python }
4. Other environment details

**Expected Output**

Data from MISP showing on OpenCTI interface
![bug](https://user-images.githubusercontent.com/54670599/63943379-d2e64e00-ca6f-11e9-901e-300ea91c53a8.png)

**Actual Output**

No data from MISP to OpenCTI platforms

**Comment by HarishHary** [comment]
Same issue as him.

```
connector-misp_1  | Request body:
connector-misp_1  | {"returnFormat": "json", "tags": {}, "withAttachments": 0, "metadata": 0, "enforceWarninglist": 0, "includeEventUuid": 0, "includeEventTags": 0, "sgReferenceOnly": 0, "includeContext": 0, "headerless": 0, "includeSightings": 0, "includeCorrelations": 0}
```

Any clue ?

**Comment by SamuelHassine** [comment]
This bug should now be solved in the last version (2.1.2). Please re-open this ticket is not.

**Comment by shahidakhter786** [comment]
> This bug should now be solved in the last version (2.1.2). Please re-open this ticket is not.

not solved
CRITICAL:pymisp:Unknown error: the response is not in JSON.
Something is broken server-side, please send us everything that follows (careful with the auth key):
Request headers:
{'User-Agent': 'PyMISP 2.4.167 - Python 3.10', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Cookie': 'CAKEPHP=fsgdsgfgfgfdgfgg-randomvalue-', 'Content-Length': '335', 'content-type': 'application/json'}
Request body:
{"returnFormat": "json", "page": 1, "limit": 50, "withAttachments": 0, "metadata": 0, "timestamp": 1674576553, "enforceWarninglist": 0, "includeEventUuid": 0, "includeEventTags": 0, "sgReferenceOnly": 0, "includeContext": 0, "headerless": 0, "includeSightings": 0, "includeDecayScore": 0, "includeCorrelations": 0, "excludeDecayed": 0}
Response (if any):
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"/events/restSearch"}
ERROR:root:Error fetching misp event again: Error code 500:
{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"/events/restSearch"}
INFO:root:Connector successfully run (0 events have been processed), storing state (last_run=2023-02-02T12:06:50.958109+00:00, last_event=2023-01-24T16:09:12+00:00, last_event_timestamp=1674576552)
INFO:root:Reporting work update_received work_d8428951-e1db-4904-96b3-c91e96c2f88c_2023-02-02T12:06:50.963Z
