### ISSUE TITLE
Error with Cyber Threat Coalition Connector 

### ISSUE THREAD

**Issue by cvdsouza** [OpenCTI-Platform/connectors#88]
## Description

Unable to start the CTC connector to pull data into OpenCTI. 

## Environment

1. OS - Ubuntu 18.04
2. OpenCTI version: 3.1.0
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. python3 cyber-threat-coalition.py

## Expected Output

Expected log data indicating successful pull. 

## Actual Output

```
/opt/opencti/connectors/cyber-threat-coalition/src# python3 cyber-threat-coalition.py 
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Starting ping alive thread
INFO:root:Fetching Cyber Threat Coalition vetted blacklists...
INFO:root:Loaded state: {}
ERROR:root:Invalid value for Indicator 'pattern': FAIL: Error found at line 1:128. mismatched input 'H' expecting ']'
 ```

**Comment by rguignard** [comment]
I think that the problem is that some URLs in the file https://blocklist.cyberthreatcoalition.org/vetted/url.txt are not well formatted or contains special character. Some one start with double quote and some others contains \ character that need to be escaped

**Comment by cvdsouza** [comment]
yup , it's the quotes. Will probably need a regex to grab the URLs from the feed.

**Comment by SamuelHassine** [comment]
@rguignard, this need a fix or I can close this issue?

**Comment by cvdsouza** [comment]
this is still an issue. The problem is URLs such as this : 
"http://8.81[.]199[.]35.bc[.]googleusercontent.com/itau/home/webApps_AplicationDevice.php?brazil=<?php%2013:00:12=date('H,i,s,A,z,n,m,u,d,g,o,l');%20echo'13:00:12';%20?>.dll"

The error is occurring when URLs such as the above are being bundled into the indicator : 
```
indicator = stix2.Indicator(
                            name=str(data),
                            pattern=self._OPENCTI_TYPE[opencti_type].format(str(data)),
                            labels=["malicious-activity"],
                            created_by_ref=organization,
                            object_marking_refs=[stix2.TLP_WHITE],
                            custom_properties={
                                CustomProperties.OBSERVABLE_TYPE: opencti_type,
                                CustomProperties.OBSERVABLE_VALUE: data,
                                CustomProperties.PATTERN_TYPE: pattern_type,
                                CustomProperties.TAG_TYPE: tags,
                            },
```
My current workaround has been to use the try, except clause, but it's not a solution. I'm not sure

**Comment by SamuelHassine** [comment]
We fixed a problem with URLs import in the version 3.2.0. Are you using this version?

**Comment by cvdsouza** [comment]
yes, I still see the error. I upgraded to 3.2.0 an hour back. Still seeing this : 

```
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Starting ping alive thread
INFO:root:Fetching Cyber Threat Coalition vetted blacklists...
INFO:root:Loaded state: {}
ERROR:root:Invalid value for Indicator 'pattern': FAIL: Error found at line 1:128. mismatched input 'H' expecting ']'
```

**Comment by SamuelHassine** [comment]
Yes I think it is an error of the connector itself. @rguignard any idea to fix it in the connector?

**Comment by tdr0** [comment]
Hi,

An approach would be to use `urlencode()`. I've made a patch for this to try it out and works without errors.

However, on the front-end, all URLs appear encoded. For example, the offending URL @cvdsouza posted above, now appears as:

```
[url:value = 'http://X.X.X.35.bc.googleusercontent.com/itau/home/webApps_AplicationToken.php?brazil=%5B%22%3C%3Fphp+15%3A18%3A09%3Ddate%28%27H%2Ci%2Cs%2CA%2Cz%2Cn%2Cm%2Cu%2Cd%2Cg%2Co%2Cl%27%29%22%5D']
```

You can check it out here: https://github.com/tdr0/connectors/commit/2dc40ae119f1e421ca52ab9e2606e71f04e206f8 

If its ok i can make a PR.

**Comment by SamuelHassine** [comment]
WDYT @rguignard?

**Comment by RomainGUIGNARD** [comment]
Sorry, i dont' see the message of @tdr0.
I implement the same solution, see PR: https://github.com/OpenCTI-Platform/connectors/pull/115.

1. Encode URL
2. Surround the indicator creation with a try/except in order to not block the connector

**Comment by rguignard** [comment]
Sorry, i dont' see the message of @tdr0.
I implement the same solution, see PR: #115.

Encode URL
Surround the indicator creation with a try/except in order to not block the connector

**Comment by cvdsouza** [comment]
Pulled the updated connector , and it's pulling the data in. Thank you very much for fixing it.

**Comment by G4fanhoto** [comment]
Good morning friends, how are you?
I have the same problem, has anyone found a solution?

![image](https://user-images.githubusercontent.com/122449332/221368540-bcff2ea7-ebbe-4886-b4a4-85c8f269544a.png)
